---
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - cumulus_interfaces
    - cumulus_quagga
   # - evpn
- hosts: spines
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - cumulus_interfaces
    - cumulus_quagga
   # - evpn
- hosts: servers
  user: vagrant
  vars:
    ansible_ssh_pass: vagrant 
  become: yes
  become_method: sudo
  roles:
    - ifupdown
