#-------------------------------------------------------------------------------
#
# Deploy a leaf device in a Unnumbered BGP fabric and advertise all networks
# via EVPN
#
#-------------------------------------------------------------------------------
---
- set_fact:
    generalvars: "{{ switchvars[inventory_hostname] }}"
    #bondvars: "{{ bondvars[inventory_hostname] }}"
    #accessvars: "{{ accessvars[inventory_hostname]  }}"

# L3 fabric 
#
- name: Clean the slate and set up unnumbered BGP fabric and VNI advertisement
  nclu:
    commands:
    - del all
    - add bgp autonomous-system {{ generalvars.ASN }}
    - add bgp router-id {{ generalvars.LOOPBACK_V4 }}
    - add loopback lo ip address {{ generalvars.LOOPBACK_V4 }}/32
    - add loopback lo clag vxlan-anycast-ip {{ generalvars.ANYCAST }}
    - add bgp ipv4 unicast network {{ generalvars.LOOPBACK_V4 }}/32
    - add loopback lo ipv6 address {{ generalvars.LOOPBACK_V6 }}/128
    - add bgp ipv6 unicast network {{ generalvars.LOOPBACK_V6 }}/128
    - add interface {{ UPLINKS }} mtu 9216
    - add bgp neighbor {{ UPLINKS }} interface remote-as external 
    - add bgp ipv4 unicast neighbor {{ UPLINKS }} activate 
    - add bgp ipv6 unicast neighbor {{ UPLINKS }} activate 
    - add bgp evpn neighbor {{ UPLINKS }} activate
    - add bgp evpn advertise-all-vni
    - add bond peerlink bond slaves swp49-50
    - add bridge bridge ports peerlink
    - add interface peerlink.4094 ip address {{ generalvars.PEERLINK_IP }}/30 
    - add interface peerlink.4094 clag peer-ip  {{ generalvars.PEERLINK_PEERIP }}
    #- add interface peerlink.4094 clag backup-ip  {{ generalvars.PEERLINK_BACKUPIP }}
    - add interface peerlink.4094 clag sys-mac 44:38:39:FF:40:94
    atomic: true
    description: l3-fabric

# VLANS/VNIS
#
- name: VLANs and VTEPs
  nclu:
    commands:
    - add vxlan vtep{{ item }} vxlan id {{ item }}
    - add vxlan vtep{{ item }} vxlan local-tunnelip {{ generalvars.LOOPBACK_V4 }}
    - add vxlan vtep{{ item }} bridge access {{ item }}
    - add vxlan vtep{{ item }} bridge learning off
    - add vxlan vtep{{ item }} mtu 9216
    commit: yes
    description: VLANS and VTEPS
  with_items: "{{ VLANS }}"

# Server facing interfaces
#
- name: Bonds
  nclu:
    atomic: true
    description: Bonds
    template: |
      {% for bond in bondvars[inventory_hostname] -%}
      add clag port bond {{ bond }} interface {{ bondvars[inventory_hostname][bond].PORTS }} clag-id {{ bondvars[inventory_hostname][bond].CLAGID }}
      {% endfor %}

- name: Accessports
  nclu:
    atomic: true
    description: accessports
    template: |
      {% for port in accessvars[inventory_hostname] -%}
      add bond {{ port }} bridge access {{ accessvars[inventory_hostname][port].VLANID }}
      add bond {{ port }} stp portadminedge
      add bond {{ port }} stp bpduguard
      {% endfor %}
...
