#-------------------------------------------------------------------------------
#
# Deploy a leaf device in a Unnumbered BGP fabric and advertise all networks
# via EVPN
#
#-------------------------------------------------------------------------------
---
- set_fact:
    myvars: "{{ switchvars[inventory_hostname] }}"

# L3 fabric 
#
- name: Clean the slate and set up unnumbered BGP fabric and VNI advertisement
  nclu:
    commands:
    - del all
    - add bgp autonomous-system {{ myvars.ASN }}
    - add bgp router-id {{ myvars.LOOPBACK_V4 }}
    - add loopback lo ip address {{ myvars.LOOPBACK_V4 }}/32
    - add bgp ipv4 unicast network {{ myvars.LOOPBACK_V4 }}/32
    - add loopback lo ipv6 address {{ myvars.LOOPBACK_V6 }}/128
    - add bgp ipv6 unicast network {{ myvars.LOOPBACK_V6 }}/128
    - add interface {{ UPLINKS }} mtu 9216
    - add bgp neighbor {{ UPLINKS }} interface remote-as external 
    - add bgp ipv4 unicast neighbor {{ UPLINKS }} activate 
    - add bgp ipv6 unicast neighbor {{ UPLINKS }} activate 
    - add bgp evpn neighbor {{ UPLINKS }} activate
    - add bgp evpn advertise-all-vni
    atomic: true
    description: l3-fabric

# VLANS/VNIS
#
- name: VLANs and VTEPs
  nclu:
    commands:
    - add vxlan vtep{{ item }} vxlan id {{ item }}
    - add vxlan vtep{{ item }} vxlan local-tunnelip {{ myvars.LOOPBACK_V4 }}
    - add vxlan vtep{{ item }} bridge access {{ item }}
    - add vxlan vtep{{ item }} bridge learning off
    - add vxlan vtep{{ item }} mtu 9216
    commit: yes
    description: VLANS and VTEPS
  with_items: "{{ VLANS }}"

# MLAG config
#
- name: MLAG config
  nclu:
    commands:
    - add bond peerlink bond slaves swp49-50
{% if switchvars[inventory_hostname] == 'leaf01' %}
    - add interface peerlink.4094 ip address 169.254.1.1/30
    - add interface peerlink.4094 clag peer-ip 169.254.1.2
    - add interface peerlink.4094 clag backup-ip 192.168.0.12
{% endif %}
{% if switchvars[inventory_hostname] == 'leaf02' %}
    - add interface peerlink.4094 ip address 169.254.1.2/30
    - add interface peerlink.4094 clag peer-ip 169.254.1.1
    - add interface peerlink.4094 clag backup-ip 192.168.0.13
{% endif %}
{% if switchvars[inventory_hostname] == 'leaf03' %}
    - add interface peerlink.4094 ip address 169.254.1.1/30
    - add interface peerlink.4094 clag peer-ip 169.254.1.2
    - add interface peerlink.4094 clag backup-ip 192.168.0.14
{% endif %}
{% if switchvars[inventory_hostname] == 'leaf04' %}
    - add interface peerlink.4094 ip address 169.254.1.2/30
    - add interface peerlink.4094 clag peer-ip 169.254.1.1
    - add interface peerlink.4094 clag backup-ip 192.168.0.13
{% endif %}
    - add interface peerlink.4094 clag sys-mac 44:38:39:FF:40:94
    atomic: true
    description: MLAG peering 



# Server facing interfaces
#
#- name: Access ports
#  nclu:
#    commands:
#    - add interface {{ TRUNK_PORTS }} bridge trunk vlans {{ VLANS | join(",") }}
#    atomic: true
#    description: access ports
...
